site_name: Mootdx 
site_description: 基于 pytdx 数据接口的二次封装

theme: readthedocs

pages:
  - 快速开始: 
    - 项目概述: 'index.md'
    - 快速安装: 'setup.md'
    - 选择线路: 'quickstart.md'
  - 行情接口:
    - '标准行情': 'api/quote1.md'
    - '扩展行情': 'api/quote2.md'
    - '数据读取': 'api/reader.md'
    - '财务数据': 'api/affair.md'

  - 命令行工具:
    - '线路测试': 'cli/bestip.md'
    - '离线数据': 'cli/reader.md'
    - '行情数据': 'cli/quotes.md'
    - '财务数据': 'cli/affair.md'
    - '批量下载': 'cli/bundle.md'
