[tool.poetry]
name = "mootdx"
version = "0.9.7"
description = ""
authors = ["bopo <ibopo@126.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
httpx = "^0.23.1"
pandas = "^1.5.2"
prettytable = "^3.5.0"
tenacity = "^8.1.0"
tqdm = "^4.64.1"
PyYAML = "^6.0"
tdxpy = "^0.1.7"
py-mini-racer = "^0.6.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
bumpversion = "^0.6.0"
twine = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
