[tool.poetry]
name = "mootdx"
version = "0.3.18"
description = ""
authors = ["bopo <ibopo@126.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
